---
name: pr check

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Get list of changed files
        id: files
        run: |
          echo "::set-output name=list::$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }})"
        shell: bash

      - name: Print changed files
        run: |
          echo "Changed files in PR: ${{ steps.files.outputs.list }}"
