---
name: pr check

permissions:
  contents: read
  pull-requests: write
  id-token: write

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checklib:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install alzlibtool
        run: |
          make tools

      - name: Azure login
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Check README
        run: |
          make docs-check
        shell: bash

      - name: Check lib
        run: |
          make lib-check
        shell: bash
