---
name: pr check

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: get a list of changed files from base branch
        run: |
          git fetch --depth=1 origin main
          git fetch --depth=1 origin +refs/pull/${{ github.event.number }}/merge
          git diff --name-only origin/main...FETCH_HEAD
        id: changed-files
